test manually setting python 3.12

diff --git a/.github/workflows/snyk-scan.yml b/.github/workflows/snyk-scan.yml
--- a/.github/workflows/snyk-scan.yml
+++ b/.github/workflows/snyk-scan.yml
@@ -4,7 +4,7 @@ name: Snyk Scan
 
 on:
   push:
-    branches: ["main" ]
+    branches: ["main"]
   pull_request:
     branches: ["main"]
   schedule: # Run snyk scan daily at midnight
@@ -21,21 +21,24 @@ jobs:
       actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@master
+      - uses: actions/checkout@v3 # Check out the repository to the workflow runner
+
+      - name: Set up Python 3.12
+        uses: actions/setup-python@v4 # Use setup-python to configure Python 3.12
+        with:
+          python-version: '3.12'
+
+      - name: Install Snyk CLI
+        run: pip install snyk # Install Snyk CLI for vulnerability scanning
 
       - name: Snyk Python report vulnerabilities
-        uses: snyk/actions/python-3.10@master
         env:
-          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-        with:
-          args:
-            --sarif-file-output=snyk.sarif
-            --policy-path=.snyk
-            --severity-threshold=high # Forces fail on high-severity vulnerabilities
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} # Snyk authentication token from GitHub secrets
+        run: snyk test --sarif-file-output=snyk.sarif --policy-path=.snyk --severity-threshold=high # Forces fail on high-severity vulnerabilities
 
       # Push the Snyk Code results into GitHub Code Scanning tab
       - name: Upload result to GitHub Code Scanning
         uses: github/codeql-action/upload-sarif@v3
-        if: success() || failure()
+        if: success() || failure() # Upload results to GitHub even if the scan fails
         with:
           sarif_file: snyk.sarif
